name: osiguranje11082017_v3
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: Dzenana <email@example.com>

environment:
  sdk: '1.24.2'

dependencies:
  angular: ^4.0.0
  angular_components: ^0.6.0
  angular_router: ^1.0.0
  font_awesome: any
  firebase: any
  dson: ^0.9.0

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1


transformers:
- angular:
    entry_points: web/main.dart
- dart_to_js_script_rewriter
